fix(accessibility): fix missing alt for img
Error: An img element must have an alt attribute, except under certain conditions.
Source: Nu Html Checker